Prog: main.o PreconditionViolationException.o
	g++ -g -Wall -std=c++11 main.o PreconditionViolationException.o -o Prog
PreconditionViolationException.o: PreconditionViolationException.h PreconditionViolationException.cpp
	g++ -g -Wall -std=c++11 PreconditionViolationException.cpp
main.o: main.cpp Stack.h Stack.hpp Node.h Node.hpp StackInterface.h AnimalPen.h FarmAnimal.h
	g++ -g -Wall -std=c++11 -c main.cpp
AnimalPen.o:

FarmAnimal.o:

Cow.o:

Chicken.o:

CyberChicken.o:

